[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38690253fa908e41ae43752ddfe8995fd629eabc"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "70200cb416f0254099bebf0e6e1a015c5d4b646917c9fa0899ada2bb86988031"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8a147fbf1f2fa6ce37b75aa93a8b9a590c0aa83"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "de478079347daa11dba79d8ab47af4815b478ce523dbd5b8e444a46816fe1148"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b37a4a01a54b17060b841bfab9f6ec4484b4a3ef"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "da255510a9181d5c5bcf92afe1e5f27f4afaa05268c99c5e64781878c5e6d0e0"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0ca9a9237fbfc8066e8acdab9d6391dac5839abf"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "0608c04a9acef97fdb597e238e07ca99cec6beaca110f59c121c3d9d436e475f"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "95ab72090c4754157a39b4d24e3a5dce473fb51e"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "dd323c01964970d366fe3b25df92c4d97545319bfc47fc7ac8abf13f6a4899f8"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d804a9a365c10d6e94904dc290bdd0afcc312f3a"
julia_version = "1.10.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "2ab037f2ea949c3d9d8e34d2903b30e47216fadf71c3a231ccc7916c14a7b6bc"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "126d83b2e012542632716c7fe515c87bbd895bc5"
julia_version = "1.11.1"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "61774625c30af71665ba36f7ecfd42bcba64bfc0f533baad2b459f2013549227"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9be536626ba699644d9e3add3ea3975bcfe4f39a"
julia_version = "1.12.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "f7810a913d6cee5c379c75bf717cc2285e467d28ed6bc47ab5299b74c9d01574"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e3b9d1ec9ea69af8885c03cb670b8b683ebd32f"
julia_version = "1.13.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "cca474cca0541dcf4b4263f61ff8251e306ec9b7e27de22fc03ef19b599291b5"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "674c8eaa9a09e1fb29d0ada0c35ef37882ce92fd"
julia_version = "1.14.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "610e23344f520d2d0d8e9208e7a3f0ab21858db87851b3990c560a763aeaad6f"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.1+0/xrt_cxxwrap.v2.26.1.x86_64-w64-mingw32-cxx11-julia_version+1.14.0.tar.gz"
