[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96b26223eed4ffa1c769142f68a706b65043a0a8"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "3bb48f5e1a2559a0713103da320f72e3f1b46feb3b000261543af8e3598ef4ec"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ed7c58bd55ad7631c9c0726044d4d5f0849d4a2"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "45dcbfcc571cb85415e91aa4d58261cc6230cacc76dc971e56dfb51ec0b2b6d5"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf440420aaf4e545f0d88b78c15074b9b749150b"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "2c87f20e657f54e035b018ca13535939720646d1ad3be9d1634e6f861fe4e9e5"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5f83603553182a9d47a3f2991d33068eb8a44e3"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "e3365d9c67d3fd9e71214b50ed5b374a0325f24556b849d76a12fdb73380e7ad"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1d2d5661701e5b28a74a46f0693a190779bafd7"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "daa180092fbd5b31a5a0b5cf5e01bae0a9a53c191912829ada23d6b11a804430"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b15b44a19acfeccf15fde75d659793d2694b28b0"
julia_version = "1.10.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "c00ee426534cb115e8866e48de1fa57ee32522612190331e2f8e83ff5e5e0980"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b46881c486ccb122a3366d1cec252204a8ce7d8"
julia_version = "1.11.1"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "70821e81f15947ef688425bc9e21cb3ec31c4a766af1170e9542ff3b1750cbef"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7bf79151640255c6964be0933d806bcbb934e93"
julia_version = "1.12.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "f860145e0b9d35393c5b52f044c96ae22044fe81b3d1a4e0030c5aff2c432025"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "135f395248b04a890f716d93409eb977b0eef7b5"
julia_version = "1.13.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "3c63bcd2a563b40f7635f56a51214d44f9eb54b85f2c00e7f2dfe0dfd05642ed"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37460e284cbc28000855588fbef1ec3a8df7acbd"
julia_version = "1.14.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "e681119dc95ebc33a9dcf392475535b88c7c49c6b32f26201c8bfd0df73a0e54"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.23.0+0/xrt_cxxwrap.v2.23.0.x86_64-w64-mingw32-cxx11-julia_version+1.14.0.tar.gz"
