[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebe790bccba5a75a500795ffc73997f99e660f42"
julia_version = "1.10.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "f42562be01f25c31ddb22a8596b02345eebc4a4345f67c084eed7f8cf7cc10d5"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-linux-gnu-cxx11-julia_version+1.10.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2340c64f61a7124ffc96fbbe336320d7f9f9551b"
julia_version = "1.11.1"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "fd774623ef93ac9c97af8508ee43be175ad8ae21dbd10270b15ac3864db0534d"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-linux-gnu-cxx11-julia_version+1.11.1.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2dd3bf5eaf7e87c9c9726ef3f2e8748e4e68186"
julia_version = "1.12.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "951b14f25872b1b44111b0bc906aff7b660a7f02ac7cf052df2c45e22c2b13c7"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-linux-gnu-cxx11-julia_version+1.12.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fe16c875d122e7688c979834b6a1b852b427888"
julia_version = "1.13.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "4156001588e2b1b42c3ec37d7d4a98ea72b3406a4cc6d407a1c9053aec4d1a9c"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-linux-gnu-cxx11-julia_version+1.13.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14a335e62f2e7d1b2a5c9fbbaafc3cbecfdd464d"
julia_version = "1.14.0"
libc = "glibc"
os = "linux"

    [[xrt_cxxwrap.download]]
    sha256 = "d2b0d4ffac39e6e8d8e1e430eb21f8a558fbde826233119d52e743d424c61fe8"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-linux-gnu-cxx11-julia_version+1.14.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1e9019a70b52afd96d9f4a8a9a310069e9b149a"
julia_version = "1.10.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "fe9f82e43af148f2e20821311040b6c899f71c31f36d52fc51e30f299acc72f8"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-w64-mingw32-cxx11-julia_version+1.10.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e474a0e3ad8fd8db83915cd6b3fab97bece0c62a"
julia_version = "1.11.1"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "65d0d1caa601ad056c65c4b3558b2bb082a75f6d799fd69e82a8f96e309713ca"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-w64-mingw32-cxx11-julia_version+1.11.1.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d19f9eb6af5c7ed21da6b7040668ff8118f76c82"
julia_version = "1.12.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "49de763b4230f773bfb4abd947cc04d66b0039c997405fe99fa8c51d9758b2e7"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-w64-mingw32-cxx11-julia_version+1.12.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a5e220af6febf85a610fcc32ec9249a4ab4208d"
julia_version = "1.13.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "f2b870c6252d1238498938ac9519476bcdbbe2b16b7be341dc8b69158ef1f142"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-w64-mingw32-cxx11-julia_version+1.13.0.tar.gz"
[[xrt_cxxwrap]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "100f23f071dca85b03dd57f3eb06f606d3b00957"
julia_version = "1.14.0"
os = "windows"

    [[xrt_cxxwrap.download]]
    sha256 = "4950f9ba9571c5ba8ee94a632d94013f871520f287a4d3a925652b60a7052f76"
    url = "https://github.com/JuliaBinaryWrappers/xrt_cxxwrap_jll.jl/releases/download/xrt_cxxwrap-v2.26.0+0/xrt_cxxwrap.v2.26.0.x86_64-w64-mingw32-cxx11-julia_version+1.14.0.tar.gz"
