# Autogenerated wrapper script for xrt_cxxwrap_jll for x86_64-w64-mingw32-cxx11-julia_version+1.10.0
export libxrtwrap

using libcxxwrap_julia_jll
using xrt_jll
JLLWrappers.@generate_wrapper_header("xrt_cxxwrap")
JLLWrappers.@declare_library_product(libxrtwrap, "libxrtwrap.dll")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, xrt_jll)
    JLLWrappers.@init_library_product(
        libxrtwrap,
        "bin\\libxrtwrap.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
