# Autogenerated wrapper script for xrt_cxxwrap_jll for x86_64-linux-gnu-cxx11-julia_version+1.12.0
export libxrtwrap

using libcxxwrap_julia_jll
using xrt_jll
using Libuuid_jll
JLLWrappers.@generate_wrapper_header("xrt_cxxwrap")
JLLWrappers.@declare_library_product(libxrtwrap, "libxrtwrap.so.2.23")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, xrt_jll, Libuuid_jll)
    JLLWrappers.@init_library_product(
        libxrtwrap,
        "lib/libxrtwrap.so.2.23",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
